# Generated by Django 4.2.11 on 2024-05-18 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport', models.IntegerField()),
                ('terminal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passager_name', models.CharField(max_length=64)),
                ('passager_state', models.CharField(choices=[('0', 'Absent'), ('1', 'Checked in'), ('2', 'Closed zone'), ('3', 'Boarded')], max_length=1)),
                ('biometriccs', models.BinaryField(max_length=2048)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.flight')),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('0', 'Check-in'), ('1', 'Closed zone'), ('2', 'Boarding')], max_length=1)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.flight')),
            ],
        ),
    ]
