# Generated by Django 4.2.11 on 2024-05-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='biometriccs',
            new_name='biometrics',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='flight',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
