# Generated by Django 4.2.11 on 2024-05-19 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_biometriccs_ticket_biometrics_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='passager_name',
            new_name='passenger_name',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='passager_state',
            new_name='passenger_state',
        ),
    ]
