# Generated by Django 4.2.11 on 2024-05-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_passager_name_ticket_passenger_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='biometrics',
            field=models.CharField(max_length=2733),
        ),
    ]
